### ISSUE TITLE
Bug: The activity section is not fully visible downwards

### ISSUE THREAD

**Issue by tw4** [lumi-work/git.cow#17]
There are texts that continue as seen in the image below, but they are not visible.

The expected behavior is that only the activity part can be scrolled without breaking the page

![image](https://github.com/user-attachments/assets/07d051cb-4a09-416d-9594-54bb3ca03ab1)

**Comment by SpadeyDev** [comment]
Now you can scroll without limits. We also prevented long commit messages in the future :)

**[fixed]
[done]**
