### ISSUE TITLE
Bug: If the descriptions in the repository file are long, the design is broken.

### ISSUE THREAD

**Issue by tw4** [lumi-work/git.cow#18]
If the descriptions in the repository file are long, the design breaks down.

The expected behavior is that the design should not change according to the length of the description

![image](https://github.com/user-attachments/assets/1f37f7b4-e4b0-48d4-8298-01872f34103f)

**Comment by SpadeyDev** [comment]
I implemented a solution to ensure that the design remains consistent regardless of the length of the description. I set a fixed height for the `<div>` element and used the slice method to limit the word length. If the content exceeds this limit, it hides the excess and displays an ellipsis `(...)`, ensuring that the design does not break. 
**[fixed]**
