### ISSUE TITLE
feat: Clicking on an activity will take you to the activity.

### ISSUE THREAD

**Issue by tw4** [lumi-work/git.cow#22]
It would be nice to go to the activity that is related when I click on my activities. It might be hard to remember what I did while tracking my recent activities or to click directly to show my activities to my friends, which increases the user experience.

**Comment by chefberke** [comment]
The situation mentioned is actually exactly when you click on the icon in the activity, it redirects to that activity (I leave a visual about this in the attachment)

![Screenshot 2024-09-20 at 16 21 49](https://github.com/user-attachments/assets/f35ed0f2-716d-49a3-9be8-d38647104969)
