### ISSUE TITLE
bug: When I hover over the card with the cursor, it becomes a cursor pointer, but the href property is only available in the title.

### ISSUE THREAD

**Issue by tw4** [lumi-work/git.cow#24]
This leaves the user open to misdirection.

A simple example is when the user sees the cursor as a pointer, they perform the click behavior. After the click, the card does not take any action and the user assumes that the redirection is broken.

This creates a bad impression on the application and a bad user experience.

![image](https://github.com/user-attachments/assets/9f832218-26f7-4f76-869f-e24a4d1be043)

**Comment by SpadeyDev** [comment]
In fact, this was what was originally desired, but it was overlooked and non-functional in terms of user experience and has now been corrected
**[fixed]**
