### ISSUE TITLE
feat: The user should be able to completely disconnect from GitHub and have their data deleted

### ISSUE THREAD

**Issue by tw4** [lumi-work/git.cow#25]
For security reasons, users should know how to completely delete and remove their own accounts. User information should be deleted from the database due to data retention policy.

You can delete an account in the user settings page.

**Comment by chefberke** [comment]
The security policy mentioned actually belongs to github, when the application is logged in, all data is collected at that moment and a conclusion is drawn accordingly, if you exit the application, no data remains with us

if you want to completely unlink your account from git.cow:

github > settings > applications > authorised oauth apps > ‘lumi-works’ > revoke 

This process can be performed by following the steps.

If there is a data we collect in the future, you should have no doubt that measures will be taken as a security policy.
