### ISSUE TITLE
Bug: Profile description and Achievements are intertwined

### ISSUE THREAD

**Issue by tw4** [lumi-work/git.cow#29]
Profile description and Achievements are intertwined

There should be a distance between the expected behavior profile description and Achievements

![Screenshot 2024-09-22 at 10 02 46 PM](https://github.com/user-attachments/assets/bfc2baf5-9ee0-4ecc-bcb0-e8b3b92c24b8)

**Comment by SpadeyDev** [comment]
**[fixed]**
![image](https://github.com/user-attachments/assets/b8519646-d8ca-49bb-8077-33ff595cffee)
